_wandb:
    value:
        cli_version: 0.21.0
        code_path: code/script/run_evolution.py
        e:
            dysg97n75loahehjog5qhkj85ftdlnor:
                args:
                    - --config
                    - toy.yaml
                    - --wandb
                codePath: script/run_evolution.py
                codePathLocal: script/run_evolution.py
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "33501757440"
                        used: "8656007168"
                email: xiaozhang20030215@gmail.com
                executable: /project/6105522/xiao215/agent-tournament/venv/bin/python3
                git:
                    commit: a9b0ba068c25720643b688668efe203bf2a0b3ab
                    remote: git@github.com:Xiao215/agent-tournament.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-e6805a04-8c99-2e20-510c-3c63b85ba166
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-dee540d6-0b07-2801-c8e6-82d10ad79dc2
                host: kn169
                memory:
                    total: "2164019658752"
                os: Linux-6.8.0-54-generic-x86_64-Intel-R-_Xeon-R-_Gold_6442Y-with-glibc2.37
                program: /project/6105522/xiao215/agent-tournament/script/run_evolution.py
                python: CPython 3.10.13
                root: /project/6105522/xiao215/agent-tournament
                slurm:
                    cluster_name: killarney
                    conf: /cm/shared/apps/slurm/var/etc/killarney/slurm.conf
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    distribution: block
                    gpus_on_node: "2"
                    gtids: "0"
                    job_account: aip-rgrosse
                    job_cpus_per_node: "32"
                    job_end_time: "1754085442"
                    job_gid: "3127987"
                    job_group: xiao215
                    job_id: "384509"
                    job_name: bash
                    job_nodelist: kn169
                    job_num_nodes: "1"
                    job_partition: gpubase_h100_b1
                    job_qos: normal
                    job_start_time: "1754081842"
                    job_uid: "3127987"
                    job_user: xiao215
                    jobid: "384509"
                    launch_node_ipaddr: 10.1.6.101
                    localid: "0"
                    mem_per_node: "49152"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: kn169
                    nprocs: "1"
                    ntasks: "1"
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "40851"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "34093"
                    pty_win_col: "167"
                    pty_win_row: "18"
                    script_context: prolog_task
                    srun_comm_host: 10.1.6.101
                    srun_comm_port: "38399"
                    step_gpus: 6,7
                    step_id: "0"
                    step_launcher_port: "38399"
                    step_nodelist: kn169
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /project/6105522/xiao215/agent-tournament
                    submit_host: klogin01
                    task_pid: "3625335"
                    tasks_per_node: "1"
                    tmpdir: /tmp
                    topology_addr: kn169
                    topology_addr_pattern: node
                    tres_per_task: cpu=32
                    umask: "0027"
                startedAt: "2025-08-01T21:00:44.194891Z"
                writerId: dysg97n75loahehjog5qhkj85ftdlnor
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 11
                - 49
                - 71
                - 105
            "2":
                - 1
                - 11
                - 49
                - 71
                - 105
            "3":
                - 16
            "4": 3.10.13
            "5": 0.21.0
            "6": 4.53.3
            "10":
                - 20
            "12": 0.21.0
            "13": linux-x86_64
agents:
    value:
        - llm:
            kwargs:
                max_new_tokens: 2048
            model: Llama-3.2-3B-Instruct
          type: CoTAgent
        - llm:
            kwargs:
                max_new_tokens: 1024
            model: gemma-2-9b-it
          type: CoTAgent
        - llm:
            kwargs:
                max_new_tokens: 2048
            model: Qwen2.5-7B-Instruct
          type: IOAgent
evolution:
    value:
        initial_population: uniform
        steps: 3
game:
    value:
        kwargs:
            payoff_matrix:
                CC:
                    - 3
                    - 3
                CD:
                    - 0
                    - 5
                DC:
                    - 5
                    - 0
                DD:
                    - 1
                    - 1
        type: PrisonersDilemma
mechanism:
    value:
        type: ReputationPrisonersDilemma
