from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from typing import Sequence

from src.agent import Agent


class Game(ABC):
    """
    Base class for all games in the tournament.
    """

    @dataclass(frozen=True)
    class Move:
        """
        A record of one player's action in a single round.

        Attributes:
            name: The name of the player.
            action: The action taken by the player.
            points: The points scored by the player in this round.
            response: The full response generated by the player.
        """
        name: str
        action: Enum
        points: float
        response: str

    def __init__(
        self,
        prompt: str,
        num_players: int,
    ) -> None:
        self.prompt = prompt
        self.num_players = num_players

    @abstractmethod
    def play(self, additional_info: str, agents: Sequence[Agent]) -> list[Move]:
        """Play the game."""
        raise NotImplementedError

    def _prompt_agent(
        self,
        agent: Agent,
        additional_info: str,
    ) -> str:
        prompt = self.prompt.format(
            agent_name=agent.name,
            additional_info=additional_info,
        )
        resp = agent.chat(prompt)
        return resp

    @abstractmethod
    def _parse_action(self, agent: Agent, response: str) -> Enum:
        """Base on the game type, extract the decision made by the llm agent. If decision is not valid with regex, use the agent to generate a valid action."""
        raise NotImplementedError
