simulation:
  num_rounds: 200
  agent_type: BaseAgent

llm:
  agents:
    - model: meta-llama/Llama-3.2-3B-Instruct
      kwargs:
        max_new_tokens: 1000
    - model: google/gemma-3-4b-it
      kwargs:
        max_new_tokens: 1000
    # - model: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
    #   kwargs:
    #     temperature: 0.0
    #     max_tokens: 1000
    - model: Qwen/Qwen3-4B
      kwargs:
        max_new_tokens: 1000

payoff_matrix:
  CC: [3, 3]
  CD: [0, 5]
  DC: [5, 0]
  DD: [1, 1]
