# Prisoners' Dilemma with Repetition mechanism using OpenRouter API models

game:
  type: PrisonersDilemma
  kwargs:
    payoff_matrix:
      CC: [2, 2]
      CD: [0, 3]
      DC: [3, 0]
      DD: [1, 1]
    parallel_players: true

evolution:
  initial_population: uniform
  steps: 25

mechanism:
  type: Repetition
  kwargs:
    num_rounds: 10
    discount: 0.95
    matchup_workers: 4

agents:
  - llm:
      provider: OpenRouter
      model: openai/gpt-oss-20b
      kwargs:
        temperature: 0
    type: CoTAgent

  - llm:
      provider: OpenRouter
      model: deepseek/deepseek-chat-v3.1
      kwargs:
        temperature: 0
    type: CoTAgent
  
  - llm:
      provider: OpenRouter
      model: qwen/qwen3-next-80b-a3b-instruct
      kwargs:
        temperature: 0
    type: CoTAgent

  - llm:
      provider: OpenRouter
      model: openai/gpt-5-nano
      kwargs:
        temperature: 0
    type: CoTAgent