game:
  type: PrisonersDilemma
  kwargs:
    payoff_matrix:
      CC: [3, 3]
      CD: [0, 5]
      DC: [5, 0]
      DD: [1, 1]

evolution:
  initial_population: uniform
  steps: 50

mechanism:
  type: ReputationPrisonersDilemma

agents:
  - llm:
      model: Qwen2.5-7B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      model: Mistral-7B-Instruct-v0.3
      kwargs:
        max_new_tokens: 1024
    type: CoTAgent

  - llm:
      model: Llama-3.2-3B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      model: gemma-3-12b-it
      kwargs:
        max_new_tokens: 1024
    type: CoTAgent

  - llm:
      model: gemma-3-12b-it
      kwargs:
        max_new_tokens: 1024
    type: IOAgent

  - llm:
      model: DeepSeek-R1-Distill-Llama-8B
      kwargs:
        max_new_tokens: 4096
    type: CoTAgent

  # - llm:
  #     model: DeepSeek-R1-Distill-Llama-8B
  #     kwargs:
  #       max_new_tokens: 2048
  #   type: IOAgent
