game:
  type: PrisonersDilemma
  kwargs:
    payoff_matrix:
      CC: [2, 2]
      CD: [0, 3]
      DC: [3, 0]
      DD: [1, 1]

evolution:
  initial_population: uniform
  steps: 100

mechanism:
  type: Repetition
  kwargs:
    num_rounds: 20
    discount: 0.95

agents:
  - llm:
      provider: HFInstance
      model: Qwen2.5-7B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: Mistral-7B-Instruct-v0.3
      kwargs:
        max_new_tokens: 1024
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: Llama-3.2-3B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: gemma-2-9b-it
      kwargs:
        max_new_tokens: 1024
    type: CoTAgent

  # Deepseek is always a chain of thought agent. It will always think.
  # - llm:
  #     provider: HFInstance
  #     model: DeepSeek-R1-Distill-Llama-8B
  #     kwargs:
  #       max_new_tokens: 4096
  #   type: CoTAgent

  # Qwen3 is always a chain of thought agent. Need to have high token limit.
  # - llm:
  #     provider: HFInstance
  #     model: Qwen3-14B
  #     kwargs:
  #       max_new_tokens: 4096
  #   type: CoTAgent

  - llm:
      provider: OpenRouter
      model: openai/gpt-oss-20b:free
      kwargs:
        temperature: 0
    type: CoTAgent

  - llm:
      provider: OpenRouter
      model: deepseek/deepseek-chat-v3.1:free
      kwargs:
        temperature: 0
    type: CoTAgent
