game:
  type: PrisonersDilemma
  kwargs:
    payoff_matrix:
      CC: [2, 2]
      CD: [0, 3]
      DC: [3, 0]
      DD: [1, 1]

evolution:
  initial_population: uniform
  steps: 100

mechanism:
  type: ReputationPrisonersDilemma
  kwargs:
    num_rounds: 20
    discount: 0.95

agents:
  - llm:
      model: Qwen2.5-7B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      model: Mistral-7B-Instruct-v0.3
      kwargs:
        max_new_tokens: 1024
    type: CoTAgent

  - llm:
      model: Llama-3.2-3B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      model: gemma-2-9b-it
      kwargs:
        max_new_tokens: 1024
    type: CoTAgent

  # Deepseek is always a chain of thought agent. It will always think.
  - llm:
      model: DeepSeek-R1-Distill-Llama-8B
      kwargs:
        max_new_tokens: 4096
    type: CoTAgent

  - llm:
      model: Qwen3-14B
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent
