game:
  type: PublicGoods
  kwargs:
    multiplier: 3
    num_players: 6
    endowment: 10

evolution:
  initial_population: uniform
  steps: 300

mechanism:
  type: ReputationPublicGoods
  kwargs:
    reputation_alpha: 0.1
    reputation_beta: 0.9
    reputation_threshold: 0.5
    observation_noise: 0.1

agents:
  - llm:
      provider: HFInstance
      model: Qwen2.5-7B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: Mistral-7B-Instruct-v0.3
      kwargs:
        max_new_tokens: 1024
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: Llama-3.2-3B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: gemma-2-9b-it
      kwargs:
        max_new_tokens: 1024
    type: CoTAgent

  # Deepseek is always a chain of thought agent. It will always think.
  - llm:
      provider: HFInstance
      model: DeepSeek-R1-Distill-Llama-8B
      kwargs:
        max_new_tokens: 4096
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: Qwen3-14B
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent
