game:
  type: PublicGoods
  kwargs:
    multiplier: 2
    num_players: 3
    endowment: 1.0

evolution:
  initial_population: uniform
  steps: 10

mechanism:
  type: ReputationPublicGoods

agents:
  - llm:
      model: Llama-3.2-3B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      model: gemma-2-9b-it
      kwargs:
        max_new_tokens: 1024
    type: CoTAgent

  - llm:
      model: Qwen2.5-7B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent