game:
  type: PrisonersDilemma
  kwargs:
    payoff_matrix:
      CC: [3, 3]
      CD: [0, 5]
      DC: [5, 0]
      DD: [1, 1]

evolution:
  initial_population: uniform
  steps: 20

mechanism:
  type: ReputationPrisonersDilemma

agents:
  - llm:
      model: Llama-3.2-3B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      model: gemma-2-9b-it
      kwargs:
        max_new_tokens: 1024
    type: CoTAgent

  - llm:
      model: DeepSeek-R1-Distill-Llama-8B
      kwargs:
        max_new_tokens: 2048
    type: IOAgent