game:
  type: PrisonersDilemma
  kwargs:
    payoff_matrix:
      CC: [2, 2]
      CD: [0, 3]
      DC: [3, 0]
      DD: [1, 1]

evolution:
  initial_population: uniform
  steps: 2

mechanism:
  type: Repetition
  kwargs:
    num_rounds: 2
    discount: 0.9

agents:
  - llm:
      provider: HFInstance
      model: Meta-Llama-3.1-8B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: gemma-2-9b-it
      kwargs:
        max_new_tokens: 1024
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: Qwen2.5-7B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: IOAgent