game:
  type: PublicGoods
  kwargs:
    multiplier: 1.5

evolution:
  initial_population: uniform
  steps: 2

mechanism:
  type: ReputationPrisonersDilemma
  kwargs:
    num_rounds: 2
    discount: 0.9

agents:
  - llm:
      model: Meta-Llama-3.1-8B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      model: gemma-2-9b-it
      kwargs:
        max_new_tokens: 1024
    type: CoTAgent

  - llm:
      model: Qwen2.5-7B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: IOAgent