game:
  type: PrisonersDilemma
  kwargs:
    payoff_matrix:
      CC: [3, 3]
      CD: [0, 5]
      DC: [5, 0]
      DD: [1, 1]

evolution:
  initial_population: uniform
  steps: 2

mechanism:
  type: Disarmament
  kwargs:
    num_rounds: 2
    discount: 0.9

agents:
  - llm:
      provider: OpenRouter
      model: openai/gpt-oss-20b:free
      kwargs:
        temperature: 0
    type: CoTAgent

  - llm:
      provider: OpenRouter
      model: deepseek/deepseek-chat-v3.1:free
      kwargs:
        temperature: 0
    type: CoTAgent