game:
  type: TravellersDilemma
  kwargs:
    min_claim: 2
    num_actions: 4
    claim_spacing: 1
    bonus: 2.0

evolution:
  initial_population: uniform
  steps: 1

mechanism:
  type: NoMechanism

agents:
  - llm:
      provider: HFInstance
      model: Meta-Llama-3.1-8B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: gemma-2-9b-it
      kwargs:
        max_new_tokens: 1024
    type: CoTAgent

  - llm:
      provider: HFInstance
      model: Qwen2.5-7B-Instruct
      kwargs:
        max_new_tokens: 2048
    type: IOAgent
